spring.application.name=project_java
spring.thymeleaf.cache=false
spring.datasource.hikari.username=root
spring.datasource.hikari.password=root
spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/nnp?useSSL=false&serverTimezone=Asia/Seoul
mybatis.mapper-locations=classpath:mappers/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# *** [박하/추가] 사진첨부시 용량 제한으로 업로드 불가하여 추가
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-http-form-post-size=50MB
#${UPLOAD_PATH}는 컴퓨터 시스템에 설정된 값을 가져오겠다는 뜻입니다.
#만약 설정된 값이 없으면 콜론(:) 뒤의 기본값을 쓰라는 뜻입니다.
spring.web.resources.static-locations=file:///${UPLOAD_PATH:C:/nnp_uploads/}
spring.mvc.static-path-pattern=/uploads/**
