spring.application.name=project_java
spring.thymeleaf.cache=false
spring.datasource.hikari.username=${DB_USERNAME:root}
spring.datasource.hikari.password=${DB_PASSWORD:root}
spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mysql://${DB_URL:localhost}:3306/yummy?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
mybatis.mapper-locations=classpath:mappers/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true


spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-http-form-post-size=50MB

# 스프링이 웹에 사진을 보여줄 때 찾는 "기준 폴더"
spring.web.resources.static-locations=${STATIC_PATH:file:///C:/uploads/}
spring.mvc.static-path-pattern=/uploads/**

# 눈바디 사진이 실제로 저장되는 "진짜 폴더" (위 폴더 안에 쏙 들어가야 함!)
project.upload.path=${UPLOAD_PATH:C:/uploads/bodycam/}

project.relearn.path=${RELEARN_PATH:C:/uploads/relearn/}


# 식단 사진 저장 경로
# meal.upload.path=${MEAL_UPLOAD_PATH:/app/uploads/meal/}
meal.upload.path=${MEAL_UPLOAD_PATH:C:/uploads/meal/}


## 사진인식(테스트용)
#ai.analyze.url=${AI_ANALYZE_URL:http://ai-server:8000}
## 사진인식후 평가
#ai.gemini.url=${AI_GEMINI_URL:http://ai-server:8000}



# 로컬 테스트용 // 서버는 환경변수 적용 중
ai.meal.url=${AI_MEAL_URL:http://localhost:8000}





